import { pgTable, text, timestamp, boolean, jsonb } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: text('id').primaryKey(), // Firebase Auth UID
  email: text('email').notNull(),
  displayName: text('display_name'),
  photoURL: text('photo_url'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

export const members = pgTable('members', {
  id: text('id').primaryKey(),
  userId: text('user_id').references(() => users.id),
  foto: text('foto'),
  nomeCompleto: text('nome_completo').notNull(),
  dataNascimento: text('data_nascimento').notNull(),
  sexo: text('sexo').notNull(),
  telefone: text('telefone').notNull(),
  endereco: text('endereco').notNull(),
  bairro: text('bairro').notNull(),
  municipio: text('municipio').notNull(),
  provincia: text('provincia').notNull(),
  escola: text('escola').notNull(),
  classeEscolar: text('classe_escolar'),
  igreja: text('igreja').notNull(),
  distrito: text('distrito').notNull(),
  regiao: text('regiao').notNull(),
  cedula: text('cedula').notNull(),
  nomeEncarregado1: text('nome_encarregado_1').notNull(),
  nomeEncarregado2: text('nome_encarregado_2').notNull(),
  nomePai: text('nome_pai'),
  nomeMae: text('nome_mae'),
  contatoPai: text('contato_pai').notNull(),
  contatoMae: text('contato_mae').notNull(),
  email: text('email').notNull(),
  classe: text('classe').notNull(),
  unidade: text('unidade').notNull(),
  cargo: text('cargo').notNull(),
  dataEntrada: text('data_entrada').notNull(),
  ativo: boolean('ativo').notNull().default(true),
  observacoes: text('observacoes').notNull().default(''),
  membroBaptizado: boolean('membro_baptizado').notNull().default(false),
  numeroBaptismo: text('numero_baptismo').notNull().default(''),
  dataBaptismo: text('data_baptismo').notNull().default(''),
  classeAtual: text('classe_atual').notNull(),
  dataInvestidura: text('data_investidura').notNull().default(''),
  classesAnteriores: jsonb('classes_anteriores').notNull().default([]),
  numeroIdentificacao: text('numero_identificacao').notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

export const auditLogs = pgTable('audit_logs', {
  id: text('id').primaryKey(),
  userId: text('user_id').references(() => users.id),
  date: text('date').notNull(),
  user: text('user').notNull(),
  operation: text('operation').notNull(),
  entity: text('entity').notNull(),
  entityId: text('entity_id').notNull(),
  previousValueJson: text('previous_value_json'),
  newValueJson: text('new_value_json'),
  origin: text('origin').notNull().default('Sistema'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});
