import type { Member, AuditRecord } from "./types";

export function calcAge(dataNascimento: string): number {
  if (!dataNascimento) return 0;
  const today = new Date();
  const birth = new Date(dataNascimento);
  let age = today.getFullYear() - birth.getFullYear();
  const m = today.getMonth() - birth.getMonth();
  if (m < 0 || (m === 0 && today.getDate() < birth.getDate())) age--;
  return age;
}

export const CLASSES = [
  "Amigo",
  "Companheiro",
  "Pesquisador",
  "Pioneiro",
  "Excursionista",
  "Guia",
  "Líder",
  "Líder Master",
  "Líder Master Avançado",
];

export const CARGOS = [
  "Diretor",
  "Diretor Associado",
  "Secretário",
  "Tesoureiro",
  "Líder de Unidade",
  "Conselheiro",
  "Desbravador",
  "Outro",
];

export const emptyMember = (): Omit<Member, "id"> => ({
  foto: undefined,
  nomeCompleto: "",
  dataNascimento: "",
  sexo: "",
  telefone: "",
  endereco: "",
  bairro: "",
  municipio: "",
  provincia: "",
  escola: "",
  igreja: "",
  distrito: "",
  regiao: "",
  cedula: "",
  nomeEncarregado1: "",
  nomeEncarregado2: "",
  contatoPai: "",
  contatoMae: "",
  email: "",
  classe: "",
  unidade: "",
  cargo: "",
  dataEntrada: "",
  ativo: true,
  observacoes: "",
  membroBaptizado: false,
  numeroBaptismo: "",
  dataBaptismo: "",
  classeAtual: "",
  dataInvestidura: "",
  classesAnteriores: [
    { classe: "", data: "" },
    { classe: "", data: "" },
    { classe: "", data: "" },
  ],
  numeroIdentificacao: "",
});

export const INITIAL_MEMBERS: Member[] = [
  {
    id: "DBV-2026-001",
    numeroIdentificacao: "DBV-2026-001",
    nomeCompleto: "Gabriel António Domingos",
    dataNascimento: "2012-04-15",
    sexo: "M",
    telefone: "+244 923 456 789",
    endereco: "Rua Direita do Palanca, Casa 45",
    bairro: "Palanca",
    municipio: "Kilamba Kiaxi",
    provincia: "Luanda",
    escola: "Colégio Adventista do Palanca",
    igreja: "IASD Palanca Central",
    distrito: "Distrito Palanca",
    regiao: "Região 3",
    cedula: "008945672LA041",
    nomeEncarregado1: "António Domingos (Pai)",
    nomeEncarregado2: "Teresa Manuel (Mãe)",
    contatoPai: "+244 923 111 222",
    contatoMae: "+244 924 333 444",
    email: "gabriel.domingos@email.com",
    classe: "Pesquisador",
    classeAtual: "Pesquisador",
    unidade: "Águias Reais",
    cargo: "Capitão de Unidade",
    dataEntrada: "2022-02-10",
    ativo: true,
    observacoes: "Sem alergias conhecidas. Ótimo desempenho em nós e amarras.",
    membroBaptizado: true,
    numeroBaptismo: "BAP-4521/2023",
    dataBaptismo: "2023-11-18",
    dataInvestidura: "2024-12-05",
    classesAnteriores: [
      { classe: "Amigo", data: "2022-11-20" },
      { classe: "Companheiro", data: "2023-11-26" },
    ],
  },
  {
    id: "DBV-2026-002",
    numeroIdentificacao: "DBV-2026-002",
    nomeCompleto: "Beatriz Luísa Gaspar",
    dataNascimento: "2013-08-22",
    sexo: "F",
    telefone: "+244 931 987 654",
    endereco: "Av. Comandante Valódia, Apto 3B",
    bairro: "Kinaxixi",
    municipio: "Luanda",
    provincia: "Luanda",
    escola: "Liceu Mutu Ya Kevela",
    igreja: "IASD Central de Luanda",
    distrito: "Distrito Central",
    regiao: "Região 1",
    cedula: "009124583LA039",
    nomeEncarregado1: "Gaspar Mendes (Pai)",
    nomeEncarregado2: "Luísa Fernando (Mãe)",
    contatoPai: "+244 912 888 777",
    contatoMae: "+244 931 987 654",
    email: "beatriz.gaspar@email.com",
    classe: "Companheiro",
    classeAtual: "Companheiro",
    unidade: "Estrelas da Manhã",
    cargo: "Secretária de Unidade",
    dataEntrada: "2023-03-01",
    ativo: true,
    observacoes: "Alérgica a penicilina. Destaque em ordem unida.",
    membroBaptizado: false,
    numeroBaptismo: "",
    dataBaptismo: "",
    dataInvestidura: "2023-11-26",
    classesAnteriores: [
      { classe: "Amigo", data: "2023-11-26" },
    ],
  },
  {
    id: "DBV-2026-003",
    numeroIdentificacao: "DBV-2026-003",
    nomeCompleto: "Mateus Kiala da Silva",
    dataNascimento: "2011-01-30",
    sexo: "M",
    telefone: "+244 945 678 123",
    endereco: "Rua 17 de Setembro, Casa 12",
    bairro: "Golf 2",
    municipio: "Kilamba Kiaxi",
    provincia: "Luanda",
    escola: "Complexo Escolar Esperança",
    igreja: "IASD Golf 2",
    distrito: "Distrito Palanca",
    regiao: "Região 3",
    cedula: "007834591LA025",
    nomeEncarregado1: "Simão Kiala (Pai)",
    nomeEncarregado2: "Ana Paulo (Mãe)",
    contatoPai: "+244 945 678 123",
    contatoMae: "+244 923 000 111",
    email: "mateus.kiala@email.com",
    classe: "Pioneiro",
    classeAtual: "Pioneiro",
    unidade: "Guerreiros da Fé",
    cargo: "Desbravador",
    dataEntrada: "2021-02-15",
    ativo: true,
    observacoes: "Excelente conhecimento de fogueiras e primeiros socorros.",
    membroBaptizado: true,
    numeroBaptismo: "BAP-3982/2022",
    dataBaptismo: "2022-10-14",
    dataInvestidura: "2024-12-05",
    classesAnteriores: [
      { classe: "Amigo", data: "2021-11-28" },
      { classe: "Companheiro", data: "2022-11-20" },
      { classe: "Pesquisador", data: "2023-11-26" },
    ],
  },
  {
    id: "DBV-2026-004",
    numeroIdentificacao: "DBV-2026-004",
    nomeCompleto: "Esperança Ruth Panzo",
    dataNascimento: "2010-09-12",
    sexo: "F",
    telefone: "+244 919 234 567",
    endereco: "Bairro Nelito Soares, Rua 4",
    bairro: "Nelito Soares",
    municipio: "Rangel",
    provincia: "Luanda",
    escola: "Colégio Santa Teresinha",
    igreja: "IASD Rangel",
    distrito: "Distrito Central",
    regiao: "Região 1",
    cedula: "006712390LA018",
    nomeEncarregado1: "João Panzo (Pai)",
    nomeEncarregado2: "Maria Panzo (Mãe)",
    contatoPai: "+244 919 234 567",
    contatoMae: "+244 922 444 888",
    email: "esperanca.panzo@email.com",
    classe: "Excursionista",
    classeAtual: "Excursionista",
    unidade: "Lírios do Vale",
    cargo: "Capitã de Unidade",
    dataEntrada: "2020-03-05",
    ativo: true,
    observacoes: "Participou do Campori Nacional.",
    membroBaptizado: true,
    numeroBaptismo: "BAP-3105/2021",
    dataBaptismo: "2021-09-18",
    dataInvestidura: "2024-12-05",
    classesAnteriores: [
      { classe: "Amigo", data: "2020-11-22" },
      { classe: "Companheiro", data: "2021-11-28" },
      { classe: "Pesquisador", data: "2022-11-20" },
      { classe: "Pioneiro", data: "2023-11-26" },
    ],
  },
  {
    id: "DBV-2026-005",
    numeroIdentificacao: "DBV-2026-005",
    nomeCompleto: "Daniel Sebastião Afonso",
    dataNascimento: "2008-05-18",
    sexo: "M",
    telefone: "+244 928 765 432",
    endereco: "Urbanização Nova Vida, Rua 12, Prédio 5",
    bairro: "Nova Vida",
    municipio: "Belas",
    provincia: "Luanda",
    escola: "Instituto Médio Politécnico",
    igreja: "IASD Nova Vida",
    distrito: "Distrito Sul",
    regiao: "Região 2",
    cedula: "005423891LA015",
    nomeEncarregado1: "Sebastião Afonso (Pai)",
    nomeEncarregado2: "Doroteia Afonso (Mãe)",
    contatoPai: "+244 928 765 432",
    contatoMae: "+244 917 555 666",
    email: "daniel.afonso@email.com",
    classe: "Guia",
    classeAtual: "Guia",
    unidade: "Águias Reais",
    cargo: "Instrutor de Classe",
    dataEntrada: "2019-02-10",
    ativo: true,
    observacoes: "Candidato à investidura de Líder no final do ano.",
    membroBaptizado: true,
    numeroBaptismo: "BAP-2450/2020",
    dataBaptismo: "2020-10-31",
    dataInvestidura: "2024-12-05",
    classesAnteriores: [
      { classe: "Amigo", data: "2019-11-24" },
      { classe: "Companheiro", data: "2020-11-29" },
      { classe: "Pesquisador", data: "2021-11-28" },
      { classe: "Pioneiro", data: "2022-11-20" },
      { classe: "Excursionista", data: "2023-11-26" },
    ],
  },
  {
    id: "DBV-2026-006",
    numeroIdentificacao: "DBV-2026-006",
    nomeCompleto: "Cláudia Inês Bento",
    dataNascimento: "2014-11-03",
    sexo: "F",
    telefone: "+244 934 112 233",
    endereco: "Rua da Samba, Próximo ao Mercado",
    bairro: "Samba",
    municipio: "Luanda",
    provincia: "Luanda",
    escola: "Escola Primária 1024",
    igreja: "IASD Samba",
    distrito: "Distrito Central",
    regiao: "Região 1",
    cedula: "010234589LA045",
    nomeEncarregado1: "Inês Bento (Mãe)",
    nomeEncarregado2: "",
    contatoPai: "",
    contatoMae: "+244 934 112 233",
    email: "ines.bento@email.com",
    classe: "Amigo",
    classeAtual: "Amigo",
    unidade: "Estrelas da Manhã",
    cargo: "Desbravador",
    dataEntrada: "2025-02-01",
    ativo: false,
    observacoes: "Mudou-se temporariamente de província. Aguarda transferência.",
    membroBaptizado: false,
    numeroBaptismo: "",
    dataBaptismo: "",
    dataInvestidura: "",
    classesAnteriores: [],
  },
];

export const INITIAL_AUDIT_LOGS: AuditRecord[] = [
  {
    id: "AUD-001",
    date: "2026-02-01 09:30:00",
    user: "Diretoria do Clube",
    operation: "CREATE",
    entity: "Member",
    entityId: "DBV-2026-001",
    newValueJson: JSON.stringify({ nomeCompleto: "Gabriel António Domingos", classe: "Pesquisador" }),
    origin: "Portal Administrativo",
  },
  {
    id: "AUD-002",
    date: "2026-02-10 14:15:00",
    user: "Secretaria",
    operation: "STATUS",
    entity: "Member",
    entityId: "DBV-2026-006",
    previousValueJson: JSON.stringify({ ativo: true }),
    newValueJson: JSON.stringify({ ativo: false, motivo: "Mudança temporária" }),
    origin: "Portal Administrativo",
  },
];
